compra-certa.email.smtp.enabled=true
compra-certa.frontend.base-url=http://localhost:4200
compra-certa.auth.password-reset-validity=PT10S
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.test-connection=true
spring.datasource.url=jdbc:postgresql://localhost:5433/compra_certa_e2e
spring.datasource.username=compra_certa
spring.datasource.password=compra_certa
